version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "daily"
    ignored_updates:
      - match:
          dependency_name: "com.alexvasilkov:gesture-views"
